// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dfuhgsqnabbzxpxostcb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRmdWhnc3FuYWJienhweG9zdGNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4OTMxODQsImV4cCI6MjA2NDQ2OTE4NH0.LLd7rRHIzkr-tGHlTuMGJ-T46-YGQTw9zwd0ndIZ6Qg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);